[package]
name = "halving_keyboard"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1" , features = ["async-std"] }
gilrs = "0.11.0"
iced_futures = "0.12.0"
#iced_core = "0.13.2"